/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb -T 
Files: macbook.glb [629.72KB] > /Users/os/Desktop/leaning/dev/gsap-3d/macbook-landing-page/public/models/macbook-transformed.glb [627.9KB] (0%)
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import { useEffect, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { SRGBColorSpace, VideoTexture } from 'three'
import useMacbookStore from '../../store'
import { featureSequence, noChangeParts } from '../../constants'

// `playing` lets the parent stop video decoding while the section is offscreen.
export default function MacbookModel({ playing = true, ...props }) {
  const color = useMacbookStore((s) => s.color)
  const texture = useMacbookStore((s) => s.texture)
  const { nodes, materials, scene } = useGLTF('/models/macbook-transformed.glb')

  // One video + texture per feature, created once. Switching features only swaps
  // the material map instead of suspending to load a new video every time.
  const screens = useMemo(
    () =>
      new Map(
        featureSequence.map(({ videoPath }) => {
          const video = Object.assign(document.createElement('video'), {
            src: videoPath,
            muted: true,
            loop: true,
            playsInline: true,
            preload: 'auto',
            crossOrigin: 'anonymous',
          })
          const videoTexture = new VideoTexture(video)
          videoTexture.colorSpace = SRGBColorSpace
          return [videoPath, videoTexture]
        })
      ),
    []
  )
  const screen = screens.get(texture ?? "") ?? screens.get(featureSequence[0].videoPath)

  // Only the visible feature video decodes; the others stay paused.
  useEffect(() => {
    screens.forEach((videoTexture) => {
      const video = videoTexture.image
      if (playing && videoTexture === screen) video.play().catch(() => {})
      else video.pause()
    })
  }, [screens, screen, playing])

  useEffect(
    () => () =>
      screens.forEach((videoTexture) => {
        videoTexture.image.pause()
        videoTexture.dispose()
      }),
    [screens]
  )

  useEffect(() => {
    scene.traverse((child) => {
      if (child.isMesh && !noChangeParts.includes(child.name)) {
        child.material.color?.set(color)
      }
    })
  }, [color, scene])
  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.zhGRTuGrQoJflBD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial002} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.lmWQsEjxpsebDlK} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.LtEafgAVRolQqRw} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.iyDJFXmHelnMTbD} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.eJObPwhgFzvfaoZ} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.nDsMUuDKliqGFdU} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.CRQixVLpahJzhJc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.YYwBgwvcyZVOOAA} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.SLGkCohDDelqXBu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.WnHKXHhScfUbJQi} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.fNHiBfcxHUJCahl} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.LpqXZqhaGCeSzdu} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.gMtYExgrEUqPfln} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.PaletteMaterial003} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.JvMFZolVCdpPqjj} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_123.geometry} rotation={[Math.PI / 2, 0, 0]} >
      <meshBasicMaterial map={screen} />
      </mesh>
      <mesh geometry={nodes.Object_127.geometry} material={materials.ZCDwChwkbBfITSW} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/macbook-transformed.glb')
